/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto.menu;
import Proyecto.BD.conexion;
import java.awt.Color;
import java.awt.Graphics;
import java.sql.ResultSet;
/**
 *
 * @author vicen
 */
public class estadisticas extends javax.swing.JFrame {

    /**
     * Creates new form estadisticas
     */
    public estadisticas() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarDatos();
        mostrarDatos2();
        mostrarDatos3();
    }
    boolean bandera = false;
    int cant_recuperados=0; 
    int cant_fallecidos=0;
    int cant_cuarentena=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnGraficar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Recuperados = new javax.swing.JTextField();
        Fallecidos = new javax.swing.JTextField();
        Cuarentena = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Estadisticas");

        btnGraficar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/recursos/grafico-de-barras.png"))); // NOI18N
        btnGraficar.setText("Graficar");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        jButton5.setText("<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Recuperados.setEditable(false);

        Fallecidos.setEditable(false);

        Cuarentena.setEditable(false);

        jLabel2.setText("Fallecidos:");

        jLabel3.setText("Recuperados:");

        jLabel4.setText("Cuarentena:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(321, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGraficar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fallecidos, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Recuperados, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cuarentena, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Recuperados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fallecidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cuarentena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGraficar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarDatos(){

        conexion objConexion2= new conexion();

        try {
            ResultSet resultado= objConexion2.consultarRegistros("SELECT * FROM Pacientes WHERE estado='Recuperado'");
            while (resultado.next()) {

                Object[] oUsuario= {resultado.getString("ID"),resultado.getString("nombre"),resultado.getString("apellido_p"),resultado.getString("rut"),resultado.getString("edad"),resultado.getString("fecha_naci"),resultado.getString("fono"),resultado.getString("email"),resultado.getString("sist_salud"),resultado.getString("genero"),resultado.getString("region"),resultado.getString("fecha_pcr"),resultado.getString("enfer_cro"),resultado.getString("otras_enfer"),resultado.getString("pers_cont"),resultado.getString("estado"),resultado.getString("medicamentos"),resultado.getString("procedimientos"),resultado.getString("ID_centromedico"),resultado.getString("ID_medico"),resultado.getString("ID_residencia")};
                cant_recuperados++;                
                 
                }
        } catch (Exception e) {
            System.out.println(e);
        }
        Recuperados.setText(String.valueOf(cant_recuperados));

    }
    public void mostrarDatos2(){

        conexion objConexion2= new conexion();

        try {
            ResultSet resultado= objConexion2.consultarRegistros("SELECT * FROM Pacientes WHERE estado='Fallecido'");
            while (resultado.next()) {

                Object[] oUsuario= {resultado.getString("ID"),resultado.getString("nombre"),resultado.getString("apellido_p"),resultado.getString("rut"),resultado.getString("edad"),resultado.getString("fecha_naci"),resultado.getString("fono"),resultado.getString("email"),resultado.getString("sist_salud"),resultado.getString("genero"),resultado.getString("region"),resultado.getString("fecha_pcr"),resultado.getString("enfer_cro"),resultado.getString("otras_enfer"),resultado.getString("pers_cont"),resultado.getString("estado"),resultado.getString("medicamentos"),resultado.getString("procedimientos"),resultado.getString("ID_centromedico"),resultado.getString("ID_medico"),resultado.getString("ID_residencia")};
                cant_fallecidos++;                
                 
                }
        } catch (Exception e) {
            System.out.println(e);
        }
        Fallecidos.setText(String.valueOf(cant_fallecidos));

    }
    public void mostrarDatos3(){

        conexion objConexion2= new conexion();

        try {
            ResultSet resultado= objConexion2.consultarRegistros("SELECT * FROM Pacientes WHERE estado='Cuarentena'");
            while (resultado.next()) {

                Object[] oUsuario= {resultado.getString("ID"),resultado.getString("nombre"),resultado.getString("apellido_p"),resultado.getString("rut"),resultado.getString("edad"),resultado.getString("fecha_naci"),resultado.getString("fono"),resultado.getString("email"),resultado.getString("sist_salud"),resultado.getString("genero"),resultado.getString("region"),resultado.getString("fecha_pcr"),resultado.getString("enfer_cro"),resultado.getString("otras_enfer"),resultado.getString("pers_cont"),resultado.getString("estado"),resultado.getString("medicamentos"),resultado.getString("procedimientos"),resultado.getString("ID_centromedico"),resultado.getString("ID_medico"),resultado.getString("ID_residencia")};
                cant_cuarentena++;                
                 
                }
        } catch (Exception e) {
            System.out.println(e);
        }
        Cuarentena.setText(String.valueOf(cant_cuarentena));

    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        menu abrir = new menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        // TODO add your handling code here:
        bandera = true;
        repaint();
    }//GEN-LAST:event_btnGraficarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new estadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cuarentena;
    private javax.swing.JTextField Fallecidos;
    private javax.swing.JTextField Recuperados;
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
   
    public void paint(Graphics g){
        super.paint(g);
        if(bandera == true){
            
            String string_rojo = Fallecidos.getText();
            String string_verde = Recuperados.getText();
            String string_azul = Cuarentena.getText();
            
            int int_rojo = Integer.parseInt(string_rojo);
            int int_verde = Integer.parseInt(string_verde);
            int int_azul = Integer.parseInt(string_azul);
            
            int total_votos = int_rojo + int_verde + int_azul;
            
            int grados_rojo = int_rojo * 360 / total_votos;
            int grados_verde = int_verde * 360 / total_votos;
            int grados_azul = int_azul * 360 / total_votos;
            
            g.setColor(new Color(255, 0, 0));
            g.fillArc(25, 80, 200, 200, 0, grados_rojo);
            g.fillRect(250, 120, 20, 20);
            g.drawString("Fallecidos", 275, 135);
            
            g.setColor(new Color(0, 130, 0));
            g.fillArc(25, 80, 200, 200, grados_rojo, grados_verde);
            g.fillRect(250, 150, 20, 20);
            g.drawString("Recuperados", 275, 165);
            
            g.setColor(new Color(0, 0, 255));
            g.fillArc(25, 80, 200, 200, grados_rojo + grados_verde, grados_azul);
            g.fillRect(250, 180, 20, 20);
            g.drawString("Cuarentena", 275, 195);
        }
    }

}


