/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto.menu;
import Proyecto.BD.conexion;
import Proyecto.objetos.MedicoBL;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vicen
 */
public class medico extends javax.swing.JFrame {
    DefaultTableModel modelo,modelo2;

    public medico() {
        initComponents();
        String[] titulos= {"IDMedico","Nombre","Apellido","Especialidad","Genero","Edad","ID_centro"};
        modelo= new DefaultTableModel(null,titulos);
        tblMedico.setModel(modelo);
        this.mostrarDatos();
        this.limpiar();

        String[] titulos2= {"IDCentro", "Tipo", "Region"};
        modelo2= new DefaultTableModel(null,titulos2);
        tblCentro.setModel(modelo2);
        this.mostrarDatos2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMedico = new javax.swing.JTable();
        btnAgregar2 = new javax.swing.JButton();
        btnEditar2 = new javax.swing.JButton();
        btnEliminar2 = new javax.swing.JButton();
        btnCancelar2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        nombre_medico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        apellido_medico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        genero_medico = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edad_medico = new javax.swing.JTextField();
        especialidad_medico = new javax.swing.JComboBox<>();
        id_medico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCentro = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        idCentro_medico = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText("Añadir medico");

        tblMedico.setAutoCreateRowSorter(true);
        tblMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMedicoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMedico);

        btnAgregar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/recursos/check.png"))); // NOI18N
        btnAgregar2.setText("Añadir");
        btnAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar2ActionPerformed(evt);
            }
        });

        btnEditar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/recursos/editar.png"))); // NOI18N
        btnEditar2.setText("Editar");
        btnEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar2ActionPerformed(evt);
            }
        });

        btnEliminar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/recursos/cerrar.png"))); // NOI18N
        btnEliminar2.setText("Eliminar");
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });

        btnCancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/recursos/refresh.png"))); // NOI18N
        btnCancelar2.setText("Cancelar");
        btnCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar2ActionPerformed(evt);
            }
        });

        jButton5.setText("<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre del medico: ");

        jLabel2.setText("Apellido del medico:");

        jLabel3.setText("Especialidad: ");

        jLabel4.setText("Genero:");

        jLabel5.setText("Edad:");

        especialidad_medico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urgencia", "UCI", "Internos", "Infectologia", "Broncopulmonar", "Cardiologo", "Neurologia", "Kinesiologo", "Fonoaudiologo", "Cirujano" }));

        id_medico.setEditable(false);

        jLabel6.setText("ID:");

        tblCentro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCentro.getTableHeader().setReorderingAllowed(false);
        tblCentro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCentroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCentro);

        jLabel7.setText("ID del Centro Medico:");

        idCentro_medico.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(id_medico, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nombre_medico)
                                            .addComponent(genero_medico)
                                            .addComponent(edad_medico)
                                            .addComponent(especialidad_medico, 0, 119, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(apellido_medico, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idCentro_medico, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nombre_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(apellido_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(especialidad_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(genero_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(edad_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(idCentro_medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_medico, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(btnEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        menu abrir = new menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar2ActionPerformed
        // TODO add your handling code here:
        if (nombre_medico.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el nombre del medico", "Error", JOptionPane.WARNING_MESSAGE);
            nombre_medico.requestFocus();
        }
        else if (apellido_medico.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el apellido del medico", "Error", JOptionPane.WARNING_MESSAGE);
            apellido_medico.requestFocus();
        }
        else if (genero_medico.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el genero del medico", "Error", JOptionPane.WARNING_MESSAGE);
            genero_medico.requestFocus();
        }
        else if (edad_medico.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste la edad del medico", "Error", JOptionPane.WARNING_MESSAGE);
            genero_medico.requestFocus();
        } 
        else if (edad_medico.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste la edad del medico", "Error", JOptionPane.WARNING_MESSAGE);
            genero_medico.requestFocus();
        } 
        else if (18 > Integer.parseInt(edad_medico.getText())){
            JOptionPane.showMessageDialog(this, "No ingresaste la edad del medico es menor a 18", "Error", JOptionPane.WARNING_MESSAGE);
            genero_medico.requestFocus();
        } 
         else if (Integer.parseInt(edad_medico.getText())>65){
            JOptionPane.showMessageDialog(this, "No ingresaste la edad del medico es mayor a 65", "Error", JOptionPane.WARNING_MESSAGE);
            genero_medico.requestFocus();
        } 
        else if (idCentro_medico.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste la id del centro medico del medico", "Error", JOptionPane.WARNING_MESSAGE);
            idCentro_medico.requestFocus();
        } 
        else{
            conexion objConexion3= new conexion();

            MedicoBL medicoO= recuperarDatosGUI();

            String strSentenciaInsert= String.format("INSERT INTO Medicos (IDMedico,Nombre,Apellido,Especialidad,Genero,Edad,ID_centromedico) " 
                        + "VALUES (NULL,'%s','%s','%s','%s','%s','%s')",medicoO.getNombre(),medicoO.getApellido(),medicoO.getEspecialidad(),medicoO.getGenero(),medicoO.getEdad(),medicoO.getID_centromedico());

            objConexion3.ejecutarSentenciaSQL(strSentenciaInsert);
        
            this.mostrarDatos();
            this.limpiar();
        }   
    }//GEN-LAST:event_btnAgregar2ActionPerformed

    private void btnCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar2ActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_btnCancelar2ActionPerformed

    private void btnEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar2ActionPerformed
        // TODO add your handling code here:
        if (nombre_medico.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el nombre del medico", "Error", JOptionPane.WARNING_MESSAGE);
            nombre_medico.requestFocus();
        }
        else if (apellido_medico.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el apellido del medico", "Error", JOptionPane.WARNING_MESSAGE);
            apellido_medico.requestFocus();
        }
        else if (genero_medico.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el genero del medico", "Error", JOptionPane.WARNING_MESSAGE);
            genero_medico.requestFocus();
        }
        else if (edad_medico.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste la edad del medico", "Error", JOptionPane.WARNING_MESSAGE);
            genero_medico.requestFocus();
        } 
        else if (edad_medico.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste la edad del medico", "Error", JOptionPane.WARNING_MESSAGE);
            genero_medico.requestFocus();
        } 
        else if (18 > Integer.parseInt(edad_medico.getText())){
            JOptionPane.showMessageDialog(this, "No ingresaste la edad del medico es menor a 18", "Error", JOptionPane.WARNING_MESSAGE);
            genero_medico.requestFocus();
        } 
         else if (Integer.parseInt(edad_medico.getText())>65){
            JOptionPane.showMessageDialog(this, "No ingresaste la edad del medico es mayor a 65", "Error", JOptionPane.WARNING_MESSAGE);
            genero_medico.requestFocus();
        } 
        else if (idCentro_medico.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste la id del centro medico del medico", "Error", JOptionPane.WARNING_MESSAGE);
            idCentro_medico.requestFocus();
        } 
        else{
            conexion objConexion3= new conexion();

            MedicoBL medicoO= recuperarDatosGUI();

            String strSentenciaInsert= String.format("UPDATE Medicos SET Nombre= '%s',Apellido='%s',Especialidad='%s',Genero='%s',Edad='%s',ID_centromedico='%s' WHERE IDMedico=%d ",medicoO.getNombre(),medicoO.getApellido(),medicoO.getEspecialidad(),medicoO.getGenero(),medicoO.getEdad(),medicoO.getID_centromedico(),medicoO.getIDMedico());

            objConexion3.ejecutarSentenciaSQL(strSentenciaInsert);

            this.mostrarDatos();
            this.limpiar();
        }
    }//GEN-LAST:event_btnEditar2ActionPerformed

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        // TODO add your handling code here:
        conexion objConexion3= new conexion();

        MedicoBL medicoO = recuperarDatosGUI();

        String strSentenciaInsert= String.format("DELETE FROM Medicos WHERE IDMedico=%d ",medicoO.getIDMedico());

        objConexion3.ejecutarSentenciaSQL(strSentenciaInsert);

        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    private void tblMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMedicoMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            JTable receptor= (JTable)evt.getSource();
            
            id_medico.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
            nombre_medico.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),1).toString());
            apellido_medico.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),2).toString());   
            especialidad_medico.setSelectedItem(receptor.getModel().getValueAt(receptor.getSelectedRow(),3).toString());
            genero_medico.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),4).toString());
            edad_medico.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),5).toString());
            idCentro_medico.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),6).toString());
        }
        btnAgregar2.setEnabled(false);
        btnEditar2.setEnabled(true);
        btnEliminar2.setEnabled(true); 
    }//GEN-LAST:event_tblMedicoMouseClicked

    private void tblCentroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCentroMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            JTable receptor= (JTable)evt.getSource();
            idCentro_medico.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
        }
    }//GEN-LAST:event_tblCentroMouseClicked

    public void mostrarDatos(){
        while (modelo.getRowCount()>0) {            
            modelo.removeRow(0);
        }

        conexion objConexion3= new conexion();

        try {
            ResultSet resultado= objConexion3.consultarRegistros("SELECT * FROM Medicos");
            while (resultado.next()) {

                Object[] oUsuario= {resultado.getString("IDMedico"),resultado.getString("Nombre"),resultado.getString("Apellido"),resultado.getString("Especialidad"),resultado.getString("Genero"),resultado.getString("Edad"),resultado.getString("ID_centromedico")};
                
                modelo.addRow(oUsuario);
                }
        } catch (Exception e) {
            System.out.println(e);
        }       

    }

    public void mostrarDatos2(){
        while (modelo2.getRowCount()>0) {            
            modelo2.removeRow(0);
        }

        conexion objConexion3= new conexion();

        try {
            ResultSet resultado= objConexion3.consultarRegistros("SELECT IDCentroMedico,Tipo,Region FROM CentrosMedicos");
            while (resultado.next()) {

                Object[] oUsuario= {resultado.getString("IDCentroMedico"),resultado.getString("Tipo"),resultado.getString("Region")};
                
                modelo2.addRow(oUsuario);
                }
        } catch (Exception e) {
            System.out.println(e);
        }   
    }

    public MedicoBL recuperarDatosGUI(){
         MedicoBL medico= new MedicoBL();
  
        int IDmedico= (id_medico.getText().isEmpty())?0: Integer.parseInt(id_medico.getText());
        int edad= (edad_medico.getText().isEmpty())?0: Integer.parseInt(edad_medico.getText());
        int idcentro= (idCentro_medico.getText().isEmpty())?0: Integer.parseInt(idCentro_medico.getText());
        
        medico.setIDMedico(IDmedico);
        medico.setNombre(nombre_medico.getText());
        medico.setApellido(apellido_medico.getText());
        medico.setEspecialidad((String) especialidad_medico.getSelectedItem());
        medico.setGenero(genero_medico.getText());
        medico.setEdad(edad);
        medico.setID_centromedico(idcentro);

        return medico;

    }

    public void limpiar() {
        id_medico.setText("");
        nombre_medico.setText("");
        apellido_medico.setText("");
        especialidad_medico.setSelectedItem("Urgencia");
        genero_medico.setText("");
        edad_medico.setText("");
        idCentro_medico.setText("");
        
        btnAgregar2.setEnabled(true);
        btnEditar2.setEnabled(false);
        btnEliminar2.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido_medico;
    private javax.swing.JButton btnAgregar2;
    private javax.swing.JButton btnCancelar2;
    private javax.swing.JButton btnEditar2;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JTextField edad_medico;
    private javax.swing.JComboBox<String> especialidad_medico;
    private javax.swing.JTextField genero_medico;
    private javax.swing.JTextField idCentro_medico;
    private javax.swing.JTextField id_medico;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombre_medico;
    private javax.swing.JTable tblCentro;
    private javax.swing.JTable tblMedico;
    // End of variables declaration//GEN-END:variables
}
