package Proyecto.menu;
import Proyecto.BD.conexion;
import Proyecto.objetos.PacienteBL;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vicen
 */
public class paciente extends javax.swing.JFrame {
    DefaultTableModel modelo,modelo2,modelo3,modelo4;

    public paciente() {
        initComponents();

        String[] titulos= {"ID","Nombres","Apellido","Rut","Edad","Fecha Nacimiento","Fono","Email","Sistema de salud","Genero","Region","FechaPCR", "Enfermedades Cronicas","Otras enfermedades","Persona de contacto","Estado","Medicamentos","Procedimientos","ID_CentroMedico","ID_Medico","ID_Residencia"};
        modelo= new DefaultTableModel(null,titulos);
        tblPacientes.setModel(modelo);
        this.mostrarDatos();
        this.limpiar();

        String[] titulos2= {"ID_CentroMedico","Tipo","Region"};
        modelo2= new DefaultTableModel(null,titulos2);
        tblCentroMedico.setModel(modelo2);
        mostrarDatos2();

        String[] titulos3= {"ID_Medico","Nombre","Especialidad"};
        modelo3= new DefaultTableModel(null,titulos3);
        tblMedico.setModel(modelo3);
        mostrarDatos3();

        String[] titulos4= {"ID_Residencia","Nombre","Region"};
        modelo4= new DefaultTableModel(null,titulos4);
        tblResidencia.setModel(modelo4);
        mostrarDatos4();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField8 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        region_centroMedico = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        nombre_paciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        apellido_paciente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edad_paciente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fechaNaci_paciente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fono_paciente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        email_paciente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        enfermCro_paciente = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        otrasEnferm_paciente = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        persona_paciente = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        medic_paciente = new javax.swing.JTextField();
        procedi_paciente = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        rut_paciente = new javax.swing.JTextField();
        fechaPcr_paciente = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        id_paciente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sistem_paciente = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMedico = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCentroMedico = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        idMedico_paciente = new javax.swing.JTextField();
        idCentro_paciente = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        estado_paciente = new javax.swing.JComboBox<>();
        genero_paciente = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblResidencia = new javax.swing.JTable();
        idResidencia_paciente = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        region_paciente = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField8.setText("jTextField8");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        region_centroMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII", "Metropolitana", "XIV", "XV", "XVI" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 692, 54, 36));
        getContentPane().add(nombre_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 108, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        getContentPane().add(apellido_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 112, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Apellido:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("RUT:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 36, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Edad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        getContentPane().add(edad_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 42, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fecha de nacimiento:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        getContentPane().add(fechaNaci_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 152, 31));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText("Añadir paciente");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 19, 362, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Telefono: ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));
        getContentPane().add(fono_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 85, -1));

        jLabel12.setText("+56");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Genero:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Email:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));
        getContentPane().add(email_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 153, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Sistema de salud:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel19.setText("Fecha de PCR:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel20.setText("Enfermedades cronicas:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));
        getContentPane().add(enfermCro_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 150, -1));

        jLabel21.setText("Otras Enfermedades:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 138, -1));
        getContentPane().add(otrasEnferm_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 150, -1));

        jLabel22.setText("Persona de contacto: ");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));
        getContentPane().add(persona_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 150, -1));

        jLabel23.setText("Medicamentos: ");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));
        getContentPane().add(medic_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 170, -1));
        getContentPane().add(procedi_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 170, -1));

        jLabel24.setText("Procedimientos: ");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, -1, -1));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/recursos/check.png"))); // NOI18N
        btnAgregar.setText("Añadir");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 646, 90, 60));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 57, 455, 10));
        getContentPane().add(rut_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 99, 26));
        getContentPane().add(fechaPcr_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 150, 32));

        tblPacientes.setAutoCreateRowSorter(true);
        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPacientes.getTableHeader().setReorderingAllowed(false);
        tblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPacientesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPacientes);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 19, 672, 609));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/recursos/cerrar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(818, 646, -1, 60));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/recursos/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 646, 90, 60));

        jLabel8.setText("AAAA-MM-DD");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jLabel9.setText("AAAA-MM-DD");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/recursos/refresh.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 646, -1, 60));

        id_paciente.setEditable(false);
        getContentPane().add(id_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 660, 67, 26));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ID:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 660, 36, -1));

        sistem_paciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fonasa", "Isapre" }));
        getContentPane().add(sistem_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 111, -1));

        jLabel17.setText("(Sin punto ni guion)");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        tblMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMedicoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMedico);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 270, 320, 151));

        tblCentroMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCentroMedico.getTableHeader().setReorderingAllowed(false);
        tblCentroMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCentroMedicoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblCentroMedico);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 62, 320, 151));

        jLabel18.setText("ID del Centro Medico:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 34, -1, -1));

        jLabel25.setText("ID del Medico:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 234, -1, -1));
        getContentPane().add(idMedico_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1258, 231, 51, -1));
        getContentPane().add(idCentro_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 31, 51, -1));

        jLabel26.setText("Estado:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        estado_paciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuarentena", "Estable", "Recuperado", "Fallecido" }));
        getContentPane().add(estado_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        genero_paciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino ", "Femenino", "No binario", "Otro" }));
        getContentPane().add(genero_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 112, -1));

        tblResidencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResidencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResidenciaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblResidencia);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 489, 325, 151));
        getContentPane().add(idResidencia_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1287, 457, 51, -1));

        jLabel27.setText("ID de la residencia:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 460, -1, -1));

        region_paciente.setEditable(false);
        getContentPane().add(region_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1415, 31, 58, -1));

        jLabel16.setText("Region:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1365, 34, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        menu abrir = new menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if (nombre_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el nombre del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            nombre_paciente.requestFocus();
        }
        else if (rut_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el rut del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            rut_paciente.requestFocus();
        }
        else if (apellido_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el apellido del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            apellido_paciente.requestFocus();
        }
        else if (edad_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste la edad del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            genero_paciente.requestFocus();
        } 
        else if (fono_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el telefono del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            genero_paciente.requestFocus();
        }
        else if (fechaNaci_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresastela fecha de nacimento del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            genero_paciente.requestFocus();
        }
        else if (fechaPcr_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste la fecha de PCR del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            genero_paciente.requestFocus();
        }
        else if (idCentro_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el centro medico del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            idCentro_paciente.requestFocus();
        }
        else if (idMedico_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el medico del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            idMedico_paciente.requestFocus();
        }
        else{
            conexion objConexion2= new conexion();

            PacienteBL pacienteO= recuperarDatosGUI();

            String strSentenciaInsert= String.format("INSERT INTO Pacientes (ID,nombre,apellido_p,rut,edad,fecha_naci,fono,email,sist_salud,genero,region,fecha_pcr,enfer_cro,otras_enfer,pers_cont,estado,medicamentos,procedimientos,ID_centromedico,ID_medico,ID_residencia) " 
                        + "VALUES (NULL,'%s','%s','%d','%d','%s','%d','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s','%s')",pacienteO.getNombre(),pacienteO.getApellido_p(),pacienteO.getRut(),pacienteO.getEdad(),pacienteO.getFecha_naci(),pacienteO.getFono(),pacienteO.getEmail(),pacienteO.getSist_salud(),pacienteO.getGenero(),pacienteO.getRegion(),pacienteO.getFecha_pcr(),pacienteO.getEnfer_cron(),pacienteO.getOtras_enfer(),pacienteO.getPers_cont(),pacienteO.getEstado(),pacienteO.getMedicamentos(),pacienteO.getProcedimientos(),pacienteO.getID_centromedico(),pacienteO.getID_medico(),pacienteO.getID_residencia());

            objConexion2.ejecutarSentenciaSQL(strSentenciaInsert);

            this.mostrarDatos();
            this.limpiar();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacientesMouseClicked
        // TODO add your handling code here: 
        if(evt.getClickCount()==1){
            JTable receptor= (JTable)evt.getSource();
            
            id_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
            nombre_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),1).toString());
            apellido_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),2).toString());
            rut_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),3).toString());
            edad_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),4).toString());
            fechaNaci_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),5).toString());
            fono_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),6).toString());
            email_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),7).toString());
            sistem_paciente.setSelectedItem(receptor.getModel().getValueAt(receptor.getSelectedRow(),8).toString());
            genero_paciente.setSelectedItem(receptor.getModel().getValueAt(receptor.getSelectedRow(),9).toString());

            fechaPcr_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),11).toString());
            enfermCro_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),12).toString());
            otrasEnferm_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),13).toString());
            persona_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),14).toString());
            estado_paciente.setSelectedItem(receptor.getModel().getValueAt(receptor.getSelectedRow(),15).toString());
            medic_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),16).toString());
            procedi_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),17).toString());
            idCentro_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),18).toString());
            idMedico_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),19).toString());
            idResidencia_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),20).toString());
          
        }
        btnAgregar.setEnabled(false);
        btnEditar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_tblPacientesMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        conexion objConexion2= new conexion();
      
        PacienteBL pacienteO= recuperarDatosGUI();
     
        String strSentenciaInsert= String.format("DELETE FROM Pacientes WHERE ID=%d",pacienteO.getID());

        objConexion2.ejecutarSentenciaSQL(strSentenciaInsert);
        

        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (nombre_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el nombre del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            nombre_paciente.requestFocus();
        }
        else if (rut_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el rut del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            rut_paciente.requestFocus();
        }
        else if (apellido_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el apellido del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            apellido_paciente.requestFocus();
        }
        else if (edad_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste la edad del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            genero_paciente.requestFocus();
        } 
        else if (email_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el email del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            genero_paciente.requestFocus();
        }
        else if (fono_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el telefono del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            genero_paciente.requestFocus();
        }
        else if (fechaNaci_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresastela fecha de nacimento del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            genero_paciente.requestFocus();
        }
        else if (fechaPcr_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste la fecha de PCR del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            genero_paciente.requestFocus();
        }
        else if (idCentro_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el centro medico del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            idCentro_paciente.requestFocus();
        }
        else if (idMedico_paciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el medico del paciente", "Error", JOptionPane.WARNING_MESSAGE);
            idMedico_paciente.requestFocus();
        }
        else{
            conexion objConexion2= new conexion();

            PacienteBL pacienteO= recuperarDatosGUI();

            String strSentenciaInsert= String.format("UPDATE Pacientes SET nombre= '%s', apellido_p= '%s',rut= '%d',edad= '%d',fecha_naci= '%s',fono= '%d',email= '%s',sist_salud= '%s',genero= '%s',region='%s',fecha_pcr= '%s',enfer_cro= '%s',otras_enfer= '%s',pers_cont= '%s',estado='%s',medicamentos= '%s',procedimientos= '%s',ID_centromedico='%s',ID_medico='%s',ID_residencia='%s' WHERE ID='%d' ",pacienteO.getNombre(),pacienteO.getApellido_p(),pacienteO.getRut(),pacienteO.getEdad(),pacienteO.getFecha_naci(),pacienteO.getFono(),pacienteO.getEmail(),pacienteO.getSist_salud(),pacienteO.getGenero(),pacienteO.getRegion(),pacienteO.getFecha_pcr(),pacienteO.getEnfer_cron(),pacienteO.getOtras_enfer(),pacienteO.getPers_cont(),pacienteO.getEstado(),pacienteO.getMedicamentos(),pacienteO.getProcedimientos(),pacienteO.getID_centromedico(),pacienteO.getID_medico(),pacienteO.getID_residencia(),pacienteO.getID());

            objConexion2.ejecutarSentenciaSQL(strSentenciaInsert);

            this.mostrarDatos();
            this.limpiar();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tblMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMedicoMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            JTable receptor= (JTable)evt.getSource();
            idMedico_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
        }
    }//GEN-LAST:event_tblMedicoMouseClicked

    private void tblCentroMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCentroMedicoMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            JTable receptor= (JTable)evt.getSource();
            idCentro_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
            region_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),2).toString());
        }
    }//GEN-LAST:event_tblCentroMedicoMouseClicked

    private void tblResidenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResidenciaMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            JTable receptor= (JTable)evt.getSource();
            idResidencia_paciente.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
        }
    }//GEN-LAST:event_tblResidenciaMouseClicked

    public void mostrarDatos(){

        while (modelo.getRowCount()>0) {            
            modelo.removeRow(0);
        }

        conexion objConexion2= new conexion();

        try {
            ResultSet resultado= objConexion2.consultarRegistros("SELECT * FROM Pacientes");
            while (resultado.next()) {

                Object[] oUsuario= {resultado.getString("ID"),resultado.getString("nombre"),resultado.getString("apellido_p"),resultado.getString("rut"),resultado.getString("edad"),resultado.getString("fecha_naci"),resultado.getString("fono"),resultado.getString("email"),resultado.getString("sist_salud"),resultado.getString("genero"),resultado.getString("region"),resultado.getString("fecha_pcr"),resultado.getString("enfer_cro"),resultado.getString("otras_enfer"),resultado.getString("pers_cont"),resultado.getString("estado"),resultado.getString("medicamentos"),resultado.getString("procedimientos"),resultado.getString("ID_centromedico"),resultado.getString("ID_medico"),resultado.getString("ID_residencia")};
                
                modelo.addRow(oUsuario);
                }
        } catch (Exception e) {
            System.out.println(e);
        }       

    }

    public void mostrarDatos2(){
        while (modelo2.getRowCount()>0) {            
            modelo2.removeRow(0);
        }

        conexion objConexion2= new conexion();

        try {
            ResultSet resultado= objConexion2.consultarRegistros("SELECT IDCentroMedico,Tipo,Region FROM CentrosMedicos");
            while (resultado.next()) {

                Object[] oUsuario= {resultado.getString("IDCentroMedico"),resultado.getString("Tipo"),resultado.getString("Region")};
                
                modelo2.addRow(oUsuario);
                }
        } catch (Exception e) {
            System.out.println(e);
        }   
    }

    public void mostrarDatos3(){
        while (modelo3.getRowCount()>0) {            
            modelo3.removeRow(0);
        }

        conexion objConexion2= new conexion();

        try {
            ResultSet resultado= objConexion2.consultarRegistros("SELECT IDMedico,Nombre,Especialidad FROM Medicos");
            while (resultado.next()) {

                Object[] oUsuario= {resultado.getString("IDMedico"),resultado.getString("Nombre"),resultado.getString("Especialidad")};
                
                modelo3.addRow(oUsuario);
                }
        } catch (Exception e) {
            System.out.println(e);
        }   
    }

    public void mostrarDatos4(){
        while (modelo4.getRowCount()>0) {            
            modelo4.removeRow(0);
        }

        conexion objConexion2= new conexion();

        try {
            ResultSet resultado= objConexion2.consultarRegistros("SELECT IDResidencia,Nombre,Region FROM ResidenciaSanitaria");
            while (resultado.next()) {

                Object[] oUsuario= {resultado.getString("IDResidencia"),resultado.getString("Nombre"),resultado.getString("Region")};
                
                modelo4.addRow(oUsuario);
                }
        } catch (Exception e) {
            System.out.println(e);
        }   
    }

    public PacienteBL recuperarDatosGUI(){
        PacienteBL pacienteO= new PacienteBL();
  
        int ID= (id_paciente.getText().isEmpty())?0: Integer.parseInt(id_paciente.getText());     
        int rut= (rut_paciente.getText().isEmpty())?0: Integer.parseInt(rut_paciente.getText());

        int edad= (edad_paciente.getText().isEmpty())?0: Integer.parseInt(edad_paciente.getText());  

        int fono= (fono_paciente.getText().isEmpty())?0: Integer.parseInt(fono_paciente.getText());
        
        int idCentro=(idCentro_paciente.getText().isEmpty())?0: Integer.parseInt(idCentro_paciente.getText());    
        int idMedico=(idMedico_paciente.getText().isEmpty())?0: Integer.parseInt(idMedico_paciente.getText()); 
        int idResi= (idResidencia_paciente.getText().isEmpty())?0: Integer.parseInt(idResidencia_paciente.getText());

        pacienteO.setID(ID);
        pacienteO.setNombre(nombre_paciente.getText());
        pacienteO.setApellido_p(apellido_paciente.getText());
        pacienteO.setRut(rut);
        pacienteO.setEdad(edad);
        pacienteO.setFecha_naci(fechaNaci_paciente.getText());
        pacienteO.setFono(fono);
        pacienteO.setEmail(email_paciente.getText());
        pacienteO.setSist_salud((String) sistem_paciente.getSelectedItem());
        pacienteO.setGenero((String) genero_paciente.getSelectedItem());
        pacienteO.setRegion(region_paciente.getText());
        pacienteO.setFecha_pcr(fechaPcr_paciente.getText());
        pacienteO.setEnfer_cron(enfermCro_paciente.getText());
        pacienteO.setOtras_enfer(otrasEnferm_paciente.getText());
        pacienteO.setEstado((String) estado_paciente.getSelectedItem());
        pacienteO.setPers_cont(persona_paciente.getText());
        pacienteO.setMedicamentos(medic_paciente.getText());
        pacienteO.setProcedimientos(procedi_paciente.getText());
        pacienteO.setID_centromedico(idCentro);
        pacienteO.setID_medico(idMedico);
        pacienteO.setID_residencia(idResi);

        return pacienteO;
        
    }

    public void limpiar() {
        id_paciente.setText("");
        nombre_paciente.setText("");
        apellido_paciente.setText("");
        rut_paciente.setText("");
        edad_paciente.setText("");
        fechaNaci_paciente.setText("");
        fono_paciente.setText("");
        email_paciente.setText("");
        sistem_paciente.setSelectedItem("Fonasa");
        genero_paciente.setSelectedItem("Masculino");
        region_paciente.setText("I");
        fechaPcr_paciente.setText("");
        estado_paciente.setSelectedItem("Positivo");
        enfermCro_paciente.setText("");
        otrasEnferm_paciente.setText("");
        persona_paciente.setText("");
        medic_paciente.setText("");
        procedi_paciente.setText("");
        idCentro_paciente.setText("");
        idMedico_paciente.setText("");
        idResidencia_paciente.setText("");

        btnAgregar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido_paciente;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JTextField edad_paciente;
    private javax.swing.JTextField email_paciente;
    private javax.swing.JTextField enfermCro_paciente;
    private javax.swing.JComboBox<String> estado_paciente;
    private javax.swing.JTextField fechaNaci_paciente;
    private javax.swing.JTextField fechaPcr_paciente;
    private javax.swing.JTextField fono_paciente;
    private javax.swing.JComboBox<String> genero_paciente;
    private javax.swing.JTextField idCentro_paciente;
    private javax.swing.JTextField idMedico_paciente;
    private javax.swing.JTextField idResidencia_paciente;
    private javax.swing.JTextField id_paciente;
    private javax.swing.JButton jButton5;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField medic_paciente;
    private javax.swing.JTextField nombre_paciente;
    private javax.swing.JTextField otrasEnferm_paciente;
    private javax.swing.JTextField persona_paciente;
    private javax.swing.JTextField procedi_paciente;
    private javax.swing.JComboBox<String> region_centroMedico;
    private javax.swing.JTextField region_paciente;
    private javax.swing.JTextField rut_paciente;
    private javax.swing.JComboBox<String> sistem_paciente;
    private javax.swing.JTable tblCentroMedico;
    private javax.swing.JTable tblMedico;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JTable tblResidencia;
    // End of variables declaration//GEN-END:variables
}
