/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto.menu;

import Proyecto.BD.conexion;
import Proyecto.objetos.ResidenciaBL;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vicen
 */
public class residenciaSanitaria extends javax.swing.JFrame {
    DefaultTableModel modelo,modelo2;
    /**
     * Creates new form residenciaSanitaria
     */
    public residenciaSanitaria() {
        initComponents();

        String[] titulos= {"IDResidencia","Nombre","Direccion","Region","ID_centromedico"};
        modelo= new DefaultTableModel(null,titulos);
        tblResidencia.setModel(modelo);
        this.mostrarDatos();
        this.limpiar();

        String[] titulos2= {"ID_CentroMedico","Tipo","Region"};
        modelo2= new DefaultTableModel(null,titulos2);
        tblCentro.setModel(modelo2);
        mostrarDatos2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblResidencia = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre_residenciaSanitaria = new javax.swing.JTextField();
        direccion_residenciaSanitaria = new javax.swing.JTextField();
        id_residenciaSanitaria = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCentro = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        idCentro_residencia = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        region_Residencia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText("Añadir Residencia Sanitaria");

        tblResidencia.setAutoCreateRowSorter(true);
        tblResidencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResidencia.getTableHeader().setReorderingAllowed(false);
        tblResidencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResidenciaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblResidencia);

        jButton5.setText("<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/recursos/check.png"))); // NOI18N
        btnAgregar1.setText("Añadir");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        btnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/recursos/editar.png"))); // NOI18N
        btnEditar1.setText("Editar");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/recursos/cerrar.png"))); // NOI18N
        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Proyecto/recursos/refresh.png"))); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Direccion:");

        id_residenciaSanitaria.setEditable(false);

        jLabel6.setText("ID:");

        tblCentro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCentro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCentroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCentro);

        jLabel3.setText("ID del Centro Medico:");

        jLabel16.setText("Region:");

        region_Residencia.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(id_residenciaSanitaria, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombre_residenciaSanitaria, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(direccion_residenciaSanitaria)
                                    .addComponent(region_Residencia)))))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idCentro_residencia, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar1)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nombre_residenciaSanitaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(direccion_residenciaSanitaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(region_Residencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(idCentro_residencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_residenciaSanitaria, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(11, 11, 11)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        menu abrir = new menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        // TODO add your handling code here:
        if (nombre_residenciaSanitaria.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el nombre de la residencia sanitaria", "Error", JOptionPane.WARNING_MESSAGE);
            nombre_residenciaSanitaria.requestFocus();
        }
        else if (direccion_residenciaSanitaria.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste la direccion de la residencia sanitaria", "Error", JOptionPane.WARNING_MESSAGE);
            direccion_residenciaSanitaria.requestFocus();
        }
        else if (idCentro_residencia.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el id de la residencia sanitaria", "Error", JOptionPane.WARNING_MESSAGE);
            idCentro_residencia.requestFocus();
        } 
        else{
            conexion objConexion4= new conexion();

            ResidenciaBL residenciaSanitaria= recuperarDatosGUI();

            String strSentenciaInsert= String.format("INSERT INTO ResidenciaSanitaria (IDResidencia,Nombre,Direccion,Region,ID_centromedico) " 
                        + "VALUES (NULL,'%s','%s','%s','%s')",residenciaSanitaria.getNombre(),residenciaSanitaria.getDireccion(),residenciaSanitaria.getRegion(),residenciaSanitaria.getID_centromedico());

            objConexion4.ejecutarSentenciaSQL(strSentenciaInsert);
        
            this.mostrarDatos();
            this.limpiar();
        }
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        // TODO add your handling code here:
        if (nombre_residenciaSanitaria.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el nombre de la residencia sanitaria", "Error", JOptionPane.WARNING_MESSAGE);
            nombre_residenciaSanitaria.requestFocus();
        }
        else if (direccion_residenciaSanitaria.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste la direccion de la residencia sanitaria", "Error", JOptionPane.WARNING_MESSAGE);
            direccion_residenciaSanitaria.requestFocus();
        }
        else if (idCentro_residencia.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No ingresaste el id de la residencia sanitaria", "Error", JOptionPane.WARNING_MESSAGE);
            idCentro_residencia.requestFocus();
        } 
        else{
            conexion objConexion1= new conexion();

            ResidenciaBL residenciaSanitaria= recuperarDatosGUI();

            String strSentenciaInsert= String.format("UPDATE ResidenciaSanitaria SET Nombre= '%s', Direccion= '%s',Region='%s',ID_centromedico=%d WHERE IDResidencia=%d ",residenciaSanitaria.getNombre(),residenciaSanitaria.getDireccion(),residenciaSanitaria.getRegion(),residenciaSanitaria.getID_centromedico(),residenciaSanitaria.getIDResidencia());

            objConexion1.ejecutarSentenciaSQL(strSentenciaInsert);

            this.mostrarDatos();
            this.limpiar();
        }
        
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
        conexion objConexion4= new conexion();

        ResidenciaBL residenciaSanitaria= recuperarDatosGUI();

        String strSentenciaInsert= String.format("DELETE FROM ResidenciaSanitaria WHERE IDResidencia=%d",residenciaSanitaria.getIDResidencia());

        objConexion4.ejecutarSentenciaSQL(strSentenciaInsert);

        this.mostrarDatos();
        this.limpiar();
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void tblResidenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResidenciaMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            JTable receptor= (JTable)evt.getSource();
            
            id_residenciaSanitaria.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
            nombre_residenciaSanitaria.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),1).toString());
            direccion_residenciaSanitaria.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),2).toString());
            idCentro_residencia.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),4).toString());
             
        }
        btnAgregar1.setEnabled(false);
        btnEditar1.setEnabled(true);
        btnEliminar1.setEnabled(true); 
    }//GEN-LAST:event_tblResidenciaMouseClicked

    private void tblCentroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCentroMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            JTable receptor= (JTable)evt.getSource();
            idCentro_residencia.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
            region_Residencia.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),2).toString());
        }
    }//GEN-LAST:event_tblCentroMouseClicked

    public void mostrarDatos(){
        while (modelo.getRowCount()>0) {            
            modelo.removeRow(0);
        }

        conexion objConexion4= new conexion();

        try {
            ResultSet resultado= objConexion4.consultarRegistros("SELECT * FROM ResidenciaSanitaria");
            while (resultado.next()) {

                Object[] oUsuario= {resultado.getString("IDResidencia"),resultado.getString("Nombre"),resultado.getString("Direccion"),resultado.getString("Region"),resultado.getString("ID_centromedico")};
                
                modelo.addRow(oUsuario);
                }
        } catch (Exception e) {
            System.out.println(e);
        }       

    }    

    public void mostrarDatos2(){
        while (modelo2.getRowCount()>0) {            
            modelo2.removeRow(0);
        }

        conexion objConexion2= new conexion();

        try {
            ResultSet resultado= objConexion2.consultarRegistros("SELECT IDCentroMedico,Tipo,Region FROM CentrosMedicos");
            while (resultado.next()) {

                Object[] oUsuario= {resultado.getString("IDCentroMedico"),resultado.getString("Tipo"),resultado.getString("Region")};
                
                modelo2.addRow(oUsuario);
                }
        } catch (Exception e) {
            System.out.println(e);
        }   
    }

    public ResidenciaBL recuperarDatosGUI(){
        ResidenciaBL residenciaSanitaria= new ResidenciaBL();
  
        int IDresidencia= (id_residenciaSanitaria.getText().isEmpty())?0: Integer.parseInt(id_residenciaSanitaria.getText());
        int idCentro= (idCentro_residencia.getText().isEmpty())?0: Integer.parseInt(idCentro_residencia.getText());
        
        residenciaSanitaria.setIDResidencia(IDresidencia);
        residenciaSanitaria.setNombre(nombre_residenciaSanitaria.getText());
        residenciaSanitaria.setDireccion(direccion_residenciaSanitaria.getText());
        residenciaSanitaria.setRegion(region_Residencia.getText());
        residenciaSanitaria.setID_centromedico(idCentro);

        return residenciaSanitaria;
    }

    public void limpiar() {
        id_residenciaSanitaria.setText("");
        nombre_residenciaSanitaria.setText("");
        direccion_residenciaSanitaria.setText("");
        region_Residencia.setText("I");
        idCentro_residencia.setText("");
        
        btnAgregar1.setEnabled(true);
        btnEditar1.setEnabled(false);
        btnEliminar1.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(residenciaSanitaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(residenciaSanitaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(residenciaSanitaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(residenciaSanitaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new residenciaSanitaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JTextField direccion_residenciaSanitaria;
    private javax.swing.JTextField idCentro_residencia;
    private javax.swing.JTextField id_residenciaSanitaria;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombre_residenciaSanitaria;
    private javax.swing.JTextField region_Residencia;
    private javax.swing.JTable tblCentro;
    private javax.swing.JTable tblResidencia;
    // End of variables declaration//GEN-END:variables
}
